spring:
  datasource:
    url: ${dbUrl:${neonDbUrl:${JDBC_URL:${DB_URL:jdbc:postgresql://${dbHost:${DB_HOST:localhost}}:${dbPort:${DB_PORT:5432}}/${dbName:${DB_NAME:ceoms}}}}}}
    username: ${dbUsername:${DB_USERNAME:${DB_USER:postgres}}}
    password: ${dbPassword:${DB_PASSWORD:${DB_PASS:postgres}}}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: ${mailHost:${MAIL_HOST:localhost}}
    port: ${mailPort:${MAIL_PORT:587}}
    username: ${mailUsername:${MAIL_USERNAME:}}
    password: ${mailPassword:${MAIL_PASSWORD:}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.ceoms: WARN
